services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "tu_contraseña_redis"]
    networks:
      - caddy_network

volumes:
  redis-data:

networks:
  caddy_network:
    external: true